### ISSUE TITLE
Sup bro, was wandering how to contact you but i guess this was the only way ... 

### ISSUE THREAD

**Issue by dipanshuhappy** [Guchii/Guchii#1]
Anyways i just thinking of making some web tools to help in college life .. wandering if you would be interested... things like fake email maker and many for ....

**Comment by Guchii** [comment]
@dipanshuhappy Hello Dipanshu. I'm already involved in a lot of stuff rn. Not sure if I'd be able to give time to more new projects but I'd be super happy to help you. Leaving you with my Discord and Instagram, We can further talk there. **guchiXD#7728, @guchi_xd**  :smile:

**Comment by dipanshuhappy** [comment]
You gave the links to the only social media sites i dont use 😄  ,do you have other like whatsapp? well it won't be wise to drop whatsapp number here ... whats  your email maybe i can ask for your number there?

**Comment by Guchii** [comment]
@dipanshuhappy :sweat_smile: here, shvomsrivastava@gmail.com

Should've seen my website shivom.me sab kuchh hai udhar, even a contact form.
